//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSA.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DCSAEntities1 : DbContext
    {
        public DCSAEntities1()
            : base("name=DCSAEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblstudent> tblstudents { get; set; }
        public virtual DbSet<result> results { get; set; }
        public virtual DbSet<study_center> study_center { get; set; }
        public virtual DbSet<tblcours> tblcourses { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
