//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSA.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class study_center
    {
        public int id { get; set; }
        public Nullable<int> sl_no { get; set; }
        public string study_center_name { get; set; }
        public Nullable<int> study_center_code { get; set; }
    }
}
