//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCSA.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcours
    {
        public int cid { get; set; }
        public string course_code { get; set; }
        public string name_of_courses { get; set; }
        public Nullable<int> credits { get; set; }
        public Nullable<int> semester { get; set; }
    }
}
